services:
  weather-station:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      ORIGIN: ${ORIGIN:-http://localhost:3000}
    restart: unless-stopped
    init: true
